export const RECEIVE_VIDEO_LIST         = 'RECEIVE_VIDEO_LIST';
export const RECEIVE_VIDEO              = 'RECEIVE_VIDEO';
export const RECEIVE_VIDEO_COMMENTS     = 'RECEIVE_VIDEO_COMMENTS';
export const RECEIVE_COMMENT_PAGE_TOKEN = 'RECEIVE_COMMENT_PAGE_TOKEN';

export const RECEIVE_SEARCH_QUERY       = 'RECEIVE_SEARCH_QUERY';
export const RECEIVE_SORT_ORDER         = 'RECEIVE_SORT_ORDER';